---
defaults: &defaults
  connection:
    zookeeper: "kafka.dev:2128"
    kafka: "kafka.dev:9092"
    schema-registry: "http://kafka.dev:8081"

  kafka:
    topic: "barcode-scanner"

development:
  <<: *defaults
  kafka:
    topic: dev-barcode-scanner

production:
  <<: *defaults
